config/routes.rb
Rails.application.routes.draw do
  resources :semesters
  resources :results do
    collection do
      get :list_result
    end
  end
  resources :faculties
  resources :exams do
    collection do
      get :list_exam
    end
  end
  resources :books
  resources :students do
    collection do
      get :list_saman
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/faculty.rb
class Faculty < ApplicationRecord
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:name, :student_id, :faculty_id, :start, :semester_id, :end, :tutor)
    end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container table-responsive">
<table class="table table-bordered">
  <tr class="field">
    <td><%= form.label :name %> </td>
    <td><%= form.text_field :name %> </td>
    </tr>

  <tr class="field">
  <td>  <%= form.label :student_id %> </td>
   <td> <%= form.number_field :student_id %> </td>
   </tr>

  <tr class="field">
    <td><%= form.label :faculty_id %> </td>
   <td> <%= form.text_field :faculty_id %> </td>
    </tr>

  <tr class="field">
    <td><%= form.label :start %> </td>
    <td><%= form.datetime_select :start_date %> </td>
    </tr>

  <tr class="field">
   <td> <%= form.label :semester_id %> </td>
   <td> <%= form.number_field :semester_id %> </td>
    </tr>

  <tr class="field">
    <td><%= form.label :end %> </td>
   <td> <%= form.datetime_select :end_date %> </td>
    </tr>

  <tr class="field">
    <td><%= form.label :tutor %> </td>
    <td><%= form.text_field :tutor %> </td>
    </tr>

  <div class="actions">
    <%= form.submit %>
  </div>
  </table>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Faculties</h1>

<button class="btn btn-warning"><%= link_to 'New Faculty', new_faculty_path %></button>

<div class="container table-responsive">
<table class="table">
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>student_id</th>
      <th>faculty_id</th>
      <th>Start</th>
      <th>semester_id</th>
      <th>End</th>
      <th>Tutor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.name %></td>
        <td><%= faculty.student_id %></td>
        <td><%= faculty.faculty_id %></td>
        <td><%= faculty.start_date %></td>
        <td><%= faculty.semester_id %></td>
        <td><%= faculty.end_date %></td>
        <td><%= faculty.tutor %></td>
        <td><%= link_to 'Show', faculty %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container table-responsive ">
<table class="table table-condensed">
<tr>
  <td><strong>Name:</strong></td>
 <td> <%= @faculty.name %></td>
</tr>

<tr>
  <td><strong>student_id:</strong></td>
 <td> <%= @faculty.student_id %></td>
</tr>

<tr>
  <td><strong>faculty_id:</strong></td>
 <td> <%= @faculty.faculty_id %></td>
</tr>

<tr>
 <td> <strong>Start:</strong></td>
  <td><%= @faculty.start %></td>
</tr>

<tr>
 <td> <strong>semester_id:</strong></td>
 <td> <%= @faculty.semester_id %></td>
</tr>

<tr>
  <td><strong>End:</strong></td>
  <td><%= @faculty.end %></td>
</tr>

<tr>
  <td><strong>Tutor:</strong></td>
  <td><%= @faculty.tutor %></td>
</tr>

</table>
</div>

<%= link_to 'Edit', edit_faculty_path(@faculty) %> |
<%= link_to 'Back', faculties_path %>