config/routes.rb
Rails.application.routes.draw do
  resources :semesters
  resources :results do
    collection do
      get :list_result
    end
  end
  resources :faculties
  resources :exams do
    collection do
      get :list_exam
    end
  end
  resources :books
  resources :students do
    collection do
      get :list_saman
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/result.rb
class Result < ApplicationRecord
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  def list_result
    @results = Result.where(tutor: "saman")
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:student_id, :tutor, :faculty_id, :marks, :division, :percentage, :type, :semester_id)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container table-responsive">
<table class="table table-striped table-dark">
  <tr class="field ">
    <td><%= form.label :student_id %></td>
   <td> <%= form.number_field :student_id %></td>
  </tr>

  <tr class="field">
   <td> <%= form.label :tutor %></td>
   <td> <%= form.text_field :tutor %></td>
  </tr>

  <tr class="field">
  <td>  <%= form.label :faculty_id %></td>
 <td>   <%= form.number_field :faculty_id %></td>
</tr>

  <tr class="field">
  <td>  <%= form.label :marks %></td>
  <td>  <%= form.text_field :marks %></td>
</tr>

  <tr class="field">
   <td> <%= form.label :division %></td>
   <td> <%= form.text_field :division %></td>
</tr>

  <tr class="field">
    <td><%= form.label :percentage %></td>
   <td> <%= form.text_field :percentage %></td>
  </tr>

   <tr class="field">
    <td><%= form.label :category %></td>
   <td> <%= form.text_field :category %></td>
  </tr>

  <tr class="field">
    <td><%= form.label :semester_id %></td>
   <td> <%= form.number_field :semester_id %></td>
  </tr>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<button class="btn btn-warning">
<%= link_to 'New Result', new_result_path %>
</button>

<div class="container table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Student id</th>
      <th>Tutor</th>
      <th>Faculty id</th>
      <th>Marks</th>
      <th>Division</th>
      <th>Percentage</th>
      <th>Category</th>
      <th>Semester id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.student_id %></td>
        <td><%= result.tutor %></td>
        <td><%= result.faculty_id %></td>
        <td><%= result.marks %></td>
        <td><%= result.division %></td>
        <td><%= result.percentage %></td>
        <td><%= result.category %></td>
        <td><%= result.semester_id %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/list_result.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<button class="btn btn-warning">
<%= link_to 'New Result', new_result_path %>
</button>

<div class="container table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>student_id</th>
      <th>Tutor</th>
      <th>faculty_id</th>
      <th>Marks</th>
      <th>Division</th>
      <th>Percentage</th>
      <th>Type</th>
      <th>semester_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
             <td><%= result.student_id %></td>
        <td><%= result.tutor %></td>
        <td><%= result.faculty_id %></td>
        <td><%= result.marks %></td>
        <td><%= result.division %></td>
        <td><%= result.percentage %></td>
        <td><%= result.category %></td>
        <td><%= result.semester_id %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container table-responsive ">
<table class="table table-condensed">
<tr>
  <td><strong>Student id:</strong></td>
  <td><%= @result.student_id %></td>
</tr>

<tr>
  <td><strong>Tutor:</strong></td>
  <td><%= @result.tutor %></td>
</tr>

<tr>
  <td><strong>faculty_id:</strong></td>
  <td><%= @result.faculty_id %></td>
</tr>

<tr>
  <td><strong>Marks:</strong></td>
  <td><%= @result.marks %></td>
</tr>

<tr>
  <td><strong>Division:</strong></td>
  <td><%= @result.division %></td>
</tr>

<tr>
  <td><strong>Percentage:</strong></td>
  <td><%= @result.percentage %></td>
</tr>

<tr>
  <td><strong>Category:</strong></td>
  <td><%= @result.category %></td>
</p>

<tr>
  <td><strong>Semester id:</strong></td>
  <td><%= @result.semester_id %></td>
</tr>
</table>
</div>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>