config/routes.rb
Rails.application.routes.draw do
  resources :semesters
  resources :results do
    collection do
      get :list_result
    end
  end
  resources :faculties
  resources :exams do
    collection do
      get :list_exam
    end
  end
  resources :books
  resources :students do
    collection do
      get :list_saman
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
  #has_one :book
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  def list_exam
    @exams = Exam.where(name: "saman")
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:name, :student_id, :faculty_id, :date, :semester_id, :type, :tutor)
    end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container table-responsive ">
<table class="table table-condensed">
  <tr class="field">
    <td><%= form.label :name %></td>
    <td><%= form.text_field :name %></td>
  </tr>

  <tr class="field">
   <td> <%= form.label :student_id %></td>
   <td> <%= form.number_field :student_id %></td>
  </tr>

  <tr class="field">
    <td><%= form.label :faculty_id %></td>
    <td><%= form.text_field :faculty_id %></td>
  </tr>

  <tr class="field">
   <td> <%= form.label :examination_date %></td>
   <td> <%= form.datetime_select :examination_date %></td>
  </tr>

  <tr class="field">
   <td> <%= form.label :semester_id %></td>
    <td><%= form.number_field :semester_id %></td>
  </tr>

  <tr class="field">
   <td> <%= form.label :category%></td>
    <td><%= form.text_field :category %></td>
  </tr>

  <tr class="field">
    <td><%= form.label :tutor %></td>
    <td><%= form.text_field :tutor %></td>
  </tr>

  <div class="actions">
    <%= form.submit %>
  </div>
  </table>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exams</h1>


<button class="btn btn-warning">
<%= link_to 'New Exam', new_exam_path %>
</button>

<%= link_to 'New book', students_path, class:"btn btn-warning" %>
<div class="container table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Student id</th>
      <th>Faculty id</th>
      <th>Examination Date</th>
      <th>Semester id</th>
      <th>Category</th>
      <th>Tutor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.name %></td>
        <td><%= exam.student_id %></td>
        <td><%= exam.faculty_id %></td>
        <td><%= exam.examination_date %></td>
        <td><%= exam.semester_id %></td>
        <td><%= exam.category %></td>
        <td><%= exam.tutor %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/exams/list_exam.html.erb
<p id="notice"><%= notice %></p>

<h1>Exams</h1>


<button class="btn btn-warning">
<%= link_to 'New Exam', new_exam_path %>
</button>

<div class="container table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Student id</th>
      <th>Faculty id</th>
      <th>Examination Date</th>
      <th>Semester id</th>
      <th>Category</th>
      <th>Tutor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.name %></td>
        <td><%= exam.student_id %></td>
        <td><%= exam.faculty_id %></td>
        <td><%= exam.examination_date %></td>
        <td><%= exam.semester_id %></td>
        <td><%= exam.category %></td>
        <td><%= exam.tutor %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/exams/new.html.erb
<h1>New Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container table-responsive ">
<table class="table table-condensed">
<tr>
 <td> <strong>Name:</strong></td>
 <td> <%= @exam.name %></td>
</tr>

<tr>
 <td> <strong>student_id:</strong></td>
  <td><%= @exam.student_id %></td>
</tr>

<tr>
  <td><strong>faculty_id:</strong></td>
  <td><%= @exam.faculty_id %></td>
</tr>

<tr>
 <td> <strong>Date:</strong></td>
 <td> <%= @exam.examination_date %></td>
</tr>

<tr>
  <td><strong>semester_id:</strong></td>
 <td> <%= @exam.semester_id %></td>
</tr>

<tr>
 <td> <strong>Type:</strong></td>
 <td> <%= @exam.category %></td>
</tr>

<tr>
 <td> <strong>Tutor:</strong></td>
  <td><%= @exam.tutor %></td>
</tr>
</table>
</div>
<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>