config/routes.rb
Rails.application.routes.draw do
  resources :semesters
  resources :results do
    collection do
      get :list_result
    end
  end
  resources :faculties
  resources :exams do
    collection do
      get :list_exam
    end
  end
  resources :books
  resources :students do
    collection do
      get :list_saman
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentManagemantSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header >
<!--nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Student Managemant System</a>
    </div>
<div class="row nav">
  <div class="col-sm-1 text-light">
    <button href="#" class="btn btn-primary">Home</a>
  </div>
</div>

<div class="row nav">
  <div class="col-sm-1 text-light">
    <button href="#" class="btn btn-primary">About</a>
  </div>
</div><div class="row nav">
  <div class="col-sm-1 text-light">
    <button href="#" class="btn btn-primary">Contact</a>
  </div>
</div>

<span class="glyphicon glyphicon-user text-light">Sign Up</span> </a>
     <a href="#"><span class="glyphicon glyphicon-log-in text-light">Login</span> </a>

  </div>
</nav-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Student Management system</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto float-right">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
      <%= link_to 'Exams', exams_path, class:"nav-link" %>
      </li>
            <li class="nav-item">
      <%= link_to 'Books', books_path, class:"nav-link" %>
      </li>
       <li class="nav-item">
      <%= link_to 'Faculties', faculties_path, class:"nav-link" %>
      </li>
             <li class="nav-item">
      <%= link_to 'Results', results_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to 'Students', students_path, class:"nav-link" %>
      </li>
           <li class="nav-item">
      <%= link_to 'Semesters', semesters_path, class:"nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Select
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <button class="nav-link disabled btn btn-danger text-light" href="#">Login</button>
      </li>
    </ul>
  </div>
</nav>
</header>
    <%= yield %>
  </body>
  <footer class="footer" style="position: fixed; left: 0; bottom: 0; width: 100%; ">
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Copyright@Saman_Maharjan</a>
    </div>
<div class="row nav nav-bar">
  <div class="col-sm-1 text-light">
    <button href="#" class="btn btn-primary">Home</a>
  </div>
</div>


  </div>
</nav>
</footer>
</html>